name: Scrape and Send Email

on:
  schedule:
    - cron: '30 15 * * *' # 18:30 Türkiye saati (UTC+3)
  workflow_dispatch: # Manuel tetikleme için

jobs:
  scrape_and_mail:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scrape and mail script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          python main.py
