name: Send Test Email

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sendmail
        run: |
          sudo apt-get update
          sudo apt-get install -y sendmail

      - name: Configure sendmail
        run: |
          echo 'define(`SMART_HOST', `smtp.gmail.com')' | sudo tee -a /etc/mail/sendmail.mc
          echo 'define(`RELAY_MAILER_ARGS', `TCP $h 587')' | sudo tee -a /etc/mail/sendmail.mc
          echo 'define(`ESMTP_MAILER_ARGS', `TCP $h 587')' | sudo tee -a /etc/mail/sendmail.mc
          echo 'define(`confAUTH_MECHANISMS', `EXTERNAL GSSAPI DIGEST-MD5 CRAM-MD5 LOGIN PLAIN')' | sudo tee -a /etc/mail/sendmail.mc
          sudo make -C /etc/mail
          sudo systemctl restart sendmail

      - name: Send test email with sendmail
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          echo "Subject: Test E-postası" > email.txt
          echo "From: $EMAIL_USER" >> email.txt
          echo "To: $TO_EMAIL" >> email.txt
          echo "" >> email.txt
          echo "Bu e-posta GitHub Actions üzerinden gönderilmiştir." >> email.txt
          sendmail -f "$EMAIL_USER" "$TO_EMAIL" < email.txt
