name: Send Email with git send-email

on:
  workflow_dispatch:  # Manuel olarak tetiklemek için

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install git and sendmail
        run: |
          sudo apt-get update
          sudo apt-get install -y git sendmail

      - name: Configure git send-email
        run: |
          git config --global sendemail.smtpserver smtp.gmail.com
          git config --global sendemail.smtpserverport 587
          git config --global sendemail.smtpencryption tls
          git config --global sendemail.smtpuser ${{ secrets.EMAIL_USER }}
          git config --global sendemail.smtppass ${{ secrets.EMAIL_PASSWORD }}

      - name: Create a sample patch file
        run: |
          echo "This is a test patch." > test.patch
          git add test.patch
          git commit -m "Add test patch"

      - name: Send email with git send-email
        run: |
          git format-patch -1 --stdout | git send-email \
            --to="${{ secrets.TO_EMAIL }}" \
            --from="${{ secrets.EMAIL_USER }}" \
            --smtp-server="smtp.gmail.com" \
            --smtp-server-port=587 \
            --smtp-encryption=tls \
            --smtp-user="${{ secrets.EMAIL_USER }}" \
            --smtp-pass="${{ secrets.EMAIL_PASSWORD }}" \
            -
