name: Send Test Email

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Send test email with Python
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          python -c "
          import os
          import smtplib
          from email.mime.multipart import MIMEMultipart
          from email.mime.text import MIMEText

          EMAIL_USER = os.environ['EMAIL_USER']
          EMAIL_PASSWORD = os.environ['EMAIL_PASSWORD']
          SMTP_SERVER = os.environ['SMTP_SERVER']
          TO_EMAIL = os.environ['TO_EMAIL']

          msg = MIMEMultipart()
          msg['From'] = EMAIL_USER
          msg['To'] = TO_EMAIL
          msg['Subject'] = 'Test E-postası'
          body = 'Bu e-posta GitHub Actions üzerinden gönderilmiştir.'
          msg.attach(MIMEText(body, 'plain'))

          try:
              with smtplib.SMTP(SMTP_SERVER, 587) as server:
                  server.starttls()
                  server.login(EMAIL_USER, EMAIL_PASSWORD)
                  server.sendmail(EMAIL_USER, TO_EMAIL, msg.as_string())
              print('E-posta başarıyla gönderildi!')
          except Exception as e:
              print(f'Hata oluştu: {e}')
          "
